version: "3"
services:
  postgres_db:
    image: postgres:latest
    container_name: "postgres-demo-db"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    networks:
      - demo

  mysql_db:
    image: mysql:latest
    container_name: "mysql-demo-db"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - demo

networks:
  demo: